# Site settings
title: Hey Blog
SEOTitle: hhblog | Just try
header-img: img/new-index-bg.jpg
email: hh23485@126.com
description: "Write Codes, Save World"
keyword: ""
url: "http://blog.hhchat.cn"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
RSS: true
# weibo_username:     2296953024
# zhihu_username:     hh23485
github_username:    hh23485
#twitter_username:  huxpro
# facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                        # use Github Flavored Markdown !important

#   syntax_highlighter: rough



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: mygithublog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# # Analytics settings
# # Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# # Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Stay hungry. Stay foolish. "
sidebar-avatar: /img/hh23485_head.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "石进鹏",
        href: "http://www.shminjs.top"
    },
    {
        title: "机器学习之神",
        href: "http://csf0429.github.io"
  }
]
